name: dast

on:
  push:
    branches: [ "master" ]

jobs:

  owasp:
    name: Scan dast owasp
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Api Scan 
      run: |
        docker run --rm -v $(pwd):/zap/wrk/:rw --user root -t owasp/zap2docker-weekly zap-api-scan.py -t https://petstore3.swagger.io/api/v3/openapi.json -f openapi -m 1 -d -I -x testreport.xml -r testreport.html
    - uses: actions/upload-artifact@v3
      with:
        name: owasp
        path: testreport.*   
    - name: upload faraday
      run: |
        pip install faraday-cli
        faraday-cli auth -f ${{ secrets.FARADAY_HOST }} -u ${{ secrets.FARADAY_USER}} -p "${{ secrets.FARADAY_PASS }}"
        faraday-cli workspace create ${{ github.event.repository.name}}-${{ github.run_number}}
        faraday-cli tool report -w ${{ github.event.repository.name}}-${{ github.run_number}} testreport.xml

  hawkscan:
    name: HawkScan
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Run HawkScan
        uses: stackhawk/hawkscan-action@v2
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}