name: sast

on:
  push:
    branches: [ "master" ]

jobs:

  secrets:
    name: Scan Secret HORUSEC
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Horusec
      run: |
        curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash -s latest
        horusec start -p="./" -e="true" -o="json" -O="./horusec.json"
    - uses: actions/upload-artifact@v3
      with:
        name: horusec
        path: horusec.json
      

